// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYS9dzZCJ0RAXwtbwKeDsHZNAlvjGtHps',
    appId: '1:796819102371:web:c80314032deb010d51fd16',
    messagingSenderId: '796819102371',
    projectId: 'book-tracker-fc8ad',
    authDomain: 'book-tracker-fc8ad.firebaseapp.com',
    storageBucket: 'book-tracker-fc8ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB95xnf9lcS8oAFgj4jIlEvcXA7CN3Wk_k',
    appId: '1:796819102371:android:3859a3cac20cafd251fd16',
    messagingSenderId: '796819102371',
    projectId: 'book-tracker-fc8ad',
    storageBucket: 'book-tracker-fc8ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_HfsqAzOrt7U2pHE7rYKZsmH3xsiDbtM',
    appId: '1:796819102371:ios:3ad8f32864022c5551fd16',
    messagingSenderId: '796819102371',
    projectId: 'book-tracker-fc8ad',
    storageBucket: 'book-tracker-fc8ad.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_HfsqAzOrt7U2pHE7rYKZsmH3xsiDbtM',
    appId: '1:796819102371:ios:3ad8f32864022c5551fd16',
    messagingSenderId: '796819102371',
    projectId: 'book-tracker-fc8ad',
    storageBucket: 'book-tracker-fc8ad.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYS9dzZCJ0RAXwtbwKeDsHZNAlvjGtHps',
    appId: '1:796819102371:web:85b1c3988c0251b051fd16',
    messagingSenderId: '796819102371',
    projectId: 'book-tracker-fc8ad',
    authDomain: 'book-tracker-fc8ad.firebaseapp.com',
    storageBucket: 'book-tracker-fc8ad.firebasestorage.app',
  );

}